# Generated by Django 4.2.11 on 2024-05-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infotech", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact1", name="subject",),
        migrations.AddField(
            model_name="contact1",
            name="mobileno",
            field=models.IntegerField(null=True),
        ),
    ]
