# Generated by Django 5.0.6 on 2024-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0003_alter_contact1_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact1',
            name='mobileno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
